### ISSUE TITLE
購入履歴の記録ができるように

### ISSUE THREAD

**Issue by NB29979** [kaya-ken/Server#3]
### 概要

購入履歴を記録するDBの構築．
今回はDBを使用せずとも代替のファイルを作成するだけでよい
サーバはクライアントからユーザ名及び商品IDを受信するとユーザの購入テーブル中該当する商品IDの購入履歴を更新する．

サーバがもつ履歴テーブルと商品テーブルは以下の通り

- ユーザ名-購入商品ID-購入日時
- 購入商品ID-商品名-値段

**Comment by yuki1222yuki** [comment]
pandasを使用

https://shinyorke.hatenablog.com/entry/nyumon-pandas

**Comment by NB29979** [comment]
https://github.com/kaya-ken/Server/pull/7

**Comment by NB29979** [comment]
マージされました
